import {
  FaReact,
  FaNodeJs,
  FaHtml5,
  FaCss3Alt,
  FaGitAlt,
  FaPython,
  FaJava,
  FaDatabase,
  FaDocker,
  FaAngular,
  FaVuejs,
  FaPhp,
  FaSwift,
  FaRust,
  FaAws,
  FaFigma,
  FaSass,
  FaWordpress,
  FaJsSquare,
  FaBootstrap,
  FaLaravel,
  FaAndroid,
  FaLinux,
  FaWindows,
  FaCuttlefish,
  FaUnity,
  FaSlack,
  FaGoogle,
  FaGithub,
  FaGitlab,
  FaJenkins,
  FaDigitalOcean,
  FaShopify,
  FaTrello,
  FaMicrosoft,
  FaApple,
  FaRedhat,
  FaJira,
  FaSalesforce,
} from "react-icons/fa"; // Import icons as needed
import { RiNextjsLine } from "react-icons/ri";

export const techIcons = {
  Next: <RiNextjsLine size={35} />,
  React: <FaReact size={35} />,
  Node: <FaNodeJs size={35} />,
  HTML: <FaHtml5 size={35} />,
  CSS: <FaCss3Alt size={35} />,
  Git: <FaGitAlt size={35} />,
  Python: <FaPython size={35} />,
  Java: <FaJava size={35} />,
  Database: <FaDatabase size={35} />,
  Docker: <FaDocker size={35} />,
  Angular: <FaAngular size={35} />,
  Vue: <FaVuejs size={35} />,
  PHP: <FaPhp size={35} />,
  Swift: <FaSwift size={35} />,
  Rust: <FaRust size={35} />,
  AWS: <FaAws size={35} />,
  Figma: <FaFigma size={35} />,
  Sass: <FaSass size={35} />,
  Wordpress: <FaWordpress size={35} />,
  JavaScript: <FaJsSquare size={35} />,
  Bootstrap: <FaBootstrap size={35} />,
  Laravel: <FaLaravel size={35} />,
  Android: <FaAndroid size={35} />,
  Linux: <FaLinux size={35} />,
  Windows: <FaWindows size={35} />,
  C: <FaCuttlefish size={35} />,
  Unity: <FaUnity size={35} />,
  Slack: <FaSlack size={35} />,
  Google: <FaGoogle size={35} />,
  GitHub: <FaGithub size={35} />,
  GitLab: <FaGitlab size={35} />,
  Salesforce: <FaSalesforce size={35} />,
  Jenkins: <FaJenkins size={35} />,
  DigitalOcean: <FaDigitalOcean size={35} />,
  Shopify: <FaShopify size={35} />,
  Trello: <FaTrello size={35} />,
  Microsoft: <FaMicrosoft size={35} />,
  Apple: <FaApple size={35} />,
  RedHat: <FaRedhat size={35} />,
  Jira: <FaJira size={35} />,
};
